# Generated by Django 4.1.3 on 2022-11-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mail_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='user',
        ),
    ]
