# Generated by Django 4.1.3 on 2022-11-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_mail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='mail_from',
        ),
    ]
